# Generated by Django 6.1.1 on 2026-09-29 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_attendance_product_worksession_productionentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.CharField(choices=[('private_out', 'Private out'), ('private_in', 'Private in'), ('business_out', 'Business out'), ('business_in', 'Business in')], max_length=20)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departments.attendance')),
            ],
        ),
    ]
