# Generated by Django 6.1.1 on 2026-10-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_attendanceevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
    ]
