# Generated by Django 6.1.1 on 2026-10-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_issue_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='archieved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='is_archieved',
            field=models.BooleanField(default=False),
        ),
    ]
