# Generated by Django 6.1.1 on 2026-10-05 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0007_project_archieved_at_project_is_archieved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='archieved_at',
            new_name='archived_at',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='is_archieved',
            new_name='is_archived',
        ),
    ]
